name: native_toolchain_ninja
description: >-
  A library to generate Ninja build files for native assets and run Ninja builds.
version: 0.1.0
repository: https://github.com/knopp/native_toolchain_ninja

topics:
  - compiler
  - ffi
  - interop
  - native-assets
  - native-toolchain

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  archive: ^4.0.7
  code_assets: ^1.0.0
  crypto: ^3.0.6
  glob: ^2.1.1
  hooks: ^1.0.0
  logging: ^1.3.0
  meta: ^1.16.0
  pub_semver: ^2.2.0

dev_dependencies:
  collection: ^1.19.1
  dart_flutter_team_lints: ^3.5.2
  # native_test_helpers:
  #   path: ../native_test_helpers/
  test: ^1.25.15
  test_descriptor: ^2.0.2
